-- =====================================================================
-- Agiliza.ai - Script de criação do schema (PostgreSQL)
-- =====================================================================
-- Este script reflete o modelo mapeado pelo Entity Framework Core em
-- backend/src/HelpDesk.Api (ver Data/AppDbContext.cs e Data/Migrations).
-- Fornecido para documentação e para permitir criar o banco manualmente
-- (psql, pgAdmin, DBeaver etc.) sem depender do `dotnet ef`.
--
-- Caso prefira deixar a aplicação criar/atualizar o schema automaticamente,
-- basta subir o Postgres (docker compose up -d) e iniciar a API: o
-- Program.cs roda as migrations (Database.MigrateAsync) no startup.
--
-- Convenção de nomenclatura adotada:
--   - Tabelas no singular, em português.
--   - Chave primária = "id" + nome da tabela (idusuario, idticket, idticket_comentario).
--     Exceção: ticket_status usa apenas "idstatus".
--   - Colunas de auditoria presentes em (quase) toda tabela:
--       dt_criacao      -> data de criação do registro
--       usr_criacao     -> quem criou o registro (FK para usuario, quando aplicável)
--       dt_alteracao    -> data da última alteração
--       usr_alteracao   -> quem fez a última alteração (FK para usuario)
--       ativo           -> flag de registro ativo/inativo
--   - Em ticket_comentario, usr_criacao já representa o autor do comentário
--     (não existe uma coluna separada de "autor").
-- =====================================================================

-- Enums antigos (Role, Priority) permanecem como INTEGER nas tabelas:
--   usuario.role        1 = Admin | 2 = Agente | 3 = Solicitante
--   ticket.priority     1 = Baixa | 2 = Media | 3 = Alta | 4 = Urgente
-- Status deixou de ser enum e agora é a tabela ticket_status (ver abaixo),
-- justamente para permitir renomear ou adicionar status sem alterar código.

CREATE TABLE IF NOT EXISTS usuario (
    idusuario       uuid PRIMARY KEY,
    nome            varchar(150) NOT NULL,
    email           varchar(200) NOT NULL,
    "senhaHash"     text NOT NULL,
    role            integer NOT NULL,
    ativo           boolean NOT NULL DEFAULT true,
    dt_criacao      timestamptz NOT NULL DEFAULT now(),
    usr_criacao     uuid NULL REFERENCES usuario ("idusuario") ON DELETE RESTRICT,
    dt_alteracao    timestamptz NULL,
    usr_alteracao   uuid NULL REFERENCES usuario ("idusuario") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_usuario_email" ON usuario (email);

CREATE TABLE IF NOT EXISTS ticket_status (
    idstatus    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_status   varchar(50) NOT NULL,
    dt_criacao  timestamptz NOT NULL DEFAULT now(),
    ativo       boolean NOT NULL DEFAULT true
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ticket_status_nm_status" ON ticket_status (nm_status);

CREATE TABLE IF NOT EXISTS ticket (
    idticket                uuid PRIMARY KEY,
    titulo                   varchar(200) NOT NULL,
    descricao                text NOT NULL,
    idstatus                 integer NOT NULL REFERENCES ticket_status (idstatus) ON DELETE RESTRICT,
    priority                 integer NOT NULL DEFAULT 2,
    idusuario_solicitante    uuid NOT NULL REFERENCES usuario (idusuario) ON DELETE RESTRICT,
    idusuario_responsavel    uuid NULL REFERENCES usuario (idusuario) ON DELETE RESTRICT,
    ativo                    boolean NOT NULL DEFAULT true,
    dt_criacao               timestamptz NOT NULL DEFAULT now(),
    usr_criacao              uuid NULL REFERENCES usuario (idusuario) ON DELETE RESTRICT,
    dt_alteracao             timestamptz NULL,
    usr_alteracao            uuid NULL REFERENCES usuario (idusuario) ON DELETE RESTRICT,
    dt_fechamento            timestamptz NULL
);

CREATE INDEX IF NOT EXISTS "IX_ticket_idstatus" ON ticket (idstatus);
CREATE INDEX IF NOT EXISTS "IX_ticket_idusuario_solicitante" ON ticket (idusuario_solicitante);
CREATE INDEX IF NOT EXISTS "IX_ticket_idusuario_responsavel" ON ticket (idusuario_responsavel);

CREATE TABLE IF NOT EXISTS ticket_comentario (
    idticket_comentario  uuid PRIMARY KEY,
    idticket             uuid NOT NULL REFERENCES ticket (idticket) ON DELETE CASCADE,
    mensagem             text NOT NULL,
    ativo                boolean NOT NULL DEFAULT true,
    dt_criacao           timestamptz NOT NULL DEFAULT now(),
    usr_criacao          uuid NOT NULL REFERENCES usuario (idusuario) ON DELETE RESTRICT, -- autor do comentário
    dt_alteracao         timestamptz NULL,
    usr_alteracao        uuid NULL REFERENCES usuario (idusuario) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_ticket_comentario_idticket" ON ticket_comentario (idticket);
