// <auto-generated />
using System;
using HelpDesk.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HelpDesk.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912191348_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HelpDesk.Api.Entities.Chamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("idticket");

                    b.Property<Guid?>("AlteradoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("usr_alteracao");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("usr_criacao");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_criacao");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_fechamento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uuid")
                        .HasColumnName("idusuario_responsavel");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("idusuario_solicitante");

                    b.Property<int>("StatusChamadoId")
                        .HasColumnType("integer")
                        .HasColumnName("idstatus");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("AlteradoPorId");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("StatusChamadoId");

                    b.ToTable("ticket", (string)null);
                });

            modelBuilder.Entity("HelpDesk.Api.Entities.ChamadoComentario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("idticket_comentario");

                    b.Property<Guid?>("AlteradoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("usr_alteracao");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("usr_criacao");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("idticket");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_criacao");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensagem");

                    b.HasKey("Id");

                    b.HasIndex("AlteradoPorId");

                    b.HasIndex("AutorId");

                    b.HasIndex("ChamadoId");

                    b.ToTable("ticket_comentario", (string)null);
                });

            modelBuilder.Entity("HelpDesk.Api.Entities.StatusChamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idstatus");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_criacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nm_status");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("ticket_status", (string)null);
                });

            modelBuilder.Entity("HelpDesk.Api.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("idusuario");

                    b.Property<Guid?>("AlteradoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("usr_alteracao");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("usr_criacao");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_criacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senhaHash");

                    b.HasKey("Id");

                    b.HasIndex("AlteradoPorId");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("HelpDesk.Api.Entities.Chamado", b =>
                {
                    b.HasOne("HelpDesk.Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AlteradoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HelpDesk.Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HelpDesk.Api.Entities.Usuario", "Responsavel")
                        .WithMany("ChamadosAtribuidos")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HelpDesk.Api.Entities.Usuario", "Solicitante")
                        .WithMany("ChamadosSolicitados")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDesk.Api.Entities.StatusChamado", "Status")
                        .WithMany()
                        .HasForeignKey("StatusChamadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsavel");

                    b.Navigation("Solicitante");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HelpDesk.Api.Entities.ChamadoComentario", b =>
                {
                    b.HasOne("HelpDesk.Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AlteradoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HelpDesk.Api.Entities.Usuario", "Autor")
                        .WithMany("Comentarios")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDesk.Api.Entities.Chamado", "Chamado")
                        .WithMany("Comentarios")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Chamado");
                });

            modelBuilder.Entity("HelpDesk.Api.Entities.Usuario", b =>
                {
                    b.HasOne("HelpDesk.Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AlteradoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HelpDesk.Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HelpDesk.Api.Entities.Chamado", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("HelpDesk.Api.Entities.Usuario", b =>
                {
                    b.Navigation("ChamadosAtribuidos");

                    b.Navigation("ChamadosSolicitados");

                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
